apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
  replicas: 3
  selector:
    app: myonlineapp
    version: 2.6.1
  template:
    metadata:
      name: myapp
      labels:
        app: myonlineapp 
        version: 2.6.1 
    spec:
      containers:
        - name: myonlineapp-container 
          image: abolidasari/myimage28feb23:1
          ports:
            - containerPort: 8080
