apiVersion: v1
kind: service 
metadata: 
    name: vertex-svc
    labels: 
        app: myonlineapp
        version: 2.6.1
spec: 
  type: NodePort 
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myonlineapp
    version: 2.6.1 
